-- ROLE
INSERT INTO `ROLE` (`ROLE_ID`,`ROLE_NAME`,`IS_ACTIVE`) VALUES (1,'ADMIN',1);
INSERT INTO `ROLE` (`ROLE_ID`,`ROLE_NAME`,`IS_ACTIVE`) VALUES (2,'USER',1);

-- User 
INSERT INTO `USER` (`USER_ID`,`USER_NAME`,`PASSWORD`,`IS_ACTIVE`) VALUES (1,'user','$2a$10$QOlMHBkakFkzGV4AqOu7wO8XrVdWbvhTh5m39KC/jZc4HuQCq.j8W',1);
INSERT INTO `USER` (`USER_ID`,`USER_NAME`,`PASSWORD`,`IS_ACTIVE`) VALUES (4,'admin','$2a$10$QOlMHBkakFkzGV4AqOu7wO8XrVdWbvhTh5m39KC/jZc4HuQCq.j8W',1);
INSERT INTO `USER` (`USER_ID`,`USER_NAME`,`PASSWORD`,`IS_ACTIVE`) VALUES (16,'user2','$2a$10$lm4DqB4joAjVhvyu5L9vO.4qJh6Z6XoXJbnlT5yxnk7VEgK9r13IG',1);

-- User Role
INSERT INTO `USER_ROLE` (`USER_ID`,`ROLE_ID`) VALUES (4,1);
INSERT INTO `USER_ROLE` (`USER_ID`,`ROLE_ID`) VALUES (1,2);
INSERT INTO `USER_ROLE` (`USER_ID`,`ROLE_ID`) VALUES (16,2);

